version: '3.4'

services:
  # The Redis container for Dapr pub/sub and state store components
  redis:
    image: "redis:6.2.6-alpine"
    container_name: dapr-redis
    ports:
      - "6379:6379"

  # The Product Service App
  product-service-app:
    build:
      context: ./ProductService
      dockerfile: Dockerfile
    container_name: product-service-app
    ports:
      - "5125:5125"
    environment:
      - ASPNETCORE_URLS=http://+:5125
  
  # The Dapr sidecar for Product Service
  product-service-dapr:
    image: "daprio/daprd:latest"
    command: ["./daprd",
              "-app-id", "product-service",
              "-app-port", "5125",
              "-dapr-http-port", "3500",
              "-components-path", "/components"]
    container_name: product-service-dapr
    network_mode: "service:product-service-app"
    volumes:
      - "./dapr/components/pubsub.yaml:/components/pubsub.yaml" # Corrected path
    depends_on:
      - product-service-app
      - redis

  # The Order Service App
  order-service-app:
    build:
      context: ./OrderService
      dockerfile: Dockerfile
    container_name: order-service-app
    ports:
      - "5146:5146"
    environment:
      - ASPNETCORE_URLS=http://+:5146
  
  # The Dapr sidecar for Order Service
  order-service-dapr:
    image: "daprio/daprd:latest"
    command: ["./daprd",
              "-app-id", "order-service",
              "-app-port", "5146",
              "-dapr-http-port", "3501",
              "-components-path", "/components"]
    container_name: order-service-dapr
    network_mode: "service:order-service-app"
    volumes:
      - "./dapr/components/pubsub.yaml:/components/pubsub.yaml" # Corrected path
    depends_on:
      - order-service-app
      - redis
